name: Generate Snake Animation
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: platane/snk@v3
        with:
          github_user_name: Ajit-pawara
          outputs: |
            output/snake.svg=github-contribution-grid-snake.svg
            output/snake-dark.svg=github-contribution-grid-snake-dark.svg
          snake_color: "#00ff00"
          snake_head_color: "#ff0000"
          tail_color: "#00ff00"
          number_of_animations: 3
          commit_message: "Update snake animation 🐍"
          branch: main
